### ISSUE TITLE
getting rid of the "sharing tab" popup in chrome

### ISSUE THREAD

**Issue by kaosbeat** [ojack/hydra-standalone#30]
When sharing a tab to hydra, I get this annoying popover saying that I'm sharing a tab.

I tried to get rid of it, but it seems you need to do this when calling

[getDisplayMedia()](https://developer.mozilla.org/docs/web/api/mediadevices/getdisplaymedia)
is this doable to integrate this as an option in hydra? or default it to off? (maybe not desired)
more info >>>
https://developer.chrome.com/docs/web-platform/screen-sharing-controls/#surfaceSwitching

**Comment by ojack** [comment]
hmmm, I haven't been able to have it not show the popover --- do you have a
minimal example showing how to do this? If it is possible, it would be
great to default to off in hydra-synth!

**Comment by kaosbeat** [comment]
It seems I misread the API, it's only hiding the "share other tab" button inside of the popover.
Seems not possible, but I found have a workaround. It works fine on linux (ubuntu) but might not work exactly the same way on other linux distros. You basically start a chrome without tabs and location bar and hide its window decorations in your operation system.
steps:
1. start a chrome using the 'app' flag and your desired URL
    ` /opt/chrome-linux/chrome --app="https://www.kaotec.org"`
2. run` xprop -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "0x2, 0x0, 0x0, 0x0, 0x0" `to remove window decorations. You have to click inside the window chrome after you run the command
3. open hydra in a different window and run `initScreen()`
![image](https://github.com/ojack/hydra-standalone/assets/204628/b2dbaa66-1c7e-45ca-a19b-ca8283e3919e)
pick the window, not the tab!
4. everything should be shared without the popover, works in fullscreen too!
![image](https://github.com/ojack/hydra-standalone/assets/204628/f2455afc-db3c-4331-91e5-b19d40ce0650)
